set(0,...
'defaultfigureposition',[380 320 540 200],...
'defaultaxeslinewidth',1.4,...
'defaultaxesfontsize',10,...
'defaultlinelinewidth',1.4,...
'defaultpatchlinewidth',1.4,...
'defaultlinemarkersize',16)
rand('state',1234)
randn('state',2345)
format compact, format long

addpath('models');
addpath('methods');