clear variables

set(0,...
    'defaultfigureposition',[380 320 540 200],...
    'defaultaxeslinewidth',1.4,...
    'defaultaxesfontsize',10,...
    'defaultlinelinewidth',1.4,...
    'defaultpatchlinewidth',1.4,...
    'defaultlinemarkersize',16)

rand_seed(1234);

format compact;
format short g;

